# Generated by Django 2.1.4 on 2018-12-28 05:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0002_auto_20181228_1302'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chatinfo',
            name='chat_content',
            field=models.CharField(max_length=400),
        ),
        migrations.AlterField(
            model_name='chatinfo',
            name='user_id',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='chatinfo',
            name='user_ip',
            field=models.CharField(max_length=30),
        ),
        migrations.AlterField(
            model_name='chatinfo',
            name='user_name',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='userinfo',
            name='user_id',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='userinfo',
            name='user_ip',
            field=models.CharField(max_length=30),
        ),
        migrations.AlterField(
            model_name='userinfo',
            name='user_name',
            field=models.CharField(max_length=50),
        ),
    ]
