# Generated by Django 2.1.4 on 2018-12-28 05:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0004_auto_20181228_1305'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ChatInfo',
        ),
        migrations.DeleteModel(
            name='UserInfo',
        ),
    ]
