# Generated by Django 2.1.4 on 2018-12-28 05:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0006_author_book'),
    ]

    operations = [
        migrations.CreateModel(
            name='ChatInfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_id', models.CharField(default='用户id', max_length=50, verbose_name='用户ID')),
                ('user_name', models.CharField(default='匿名', max_length=50, verbose_name='用户名')),
                ('user_ip', models.CharField(default='0', max_length=30, verbose_name='用户IP')),
                ('chat_content', models.CharField(default='空', max_length=400, verbose_name='发送的内容')),
            ],
            options={
                'verbose_name': '聊天内容',
                'verbose_name_plural': '聊天内容',
            },
        ),
        migrations.CreateModel(
            name='UserInfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_id', models.CharField(default='用户id', max_length=50, verbose_name='用户ID')),
                ('user_name', models.CharField(default='匿名用户', max_length=50, verbose_name='用户名')),
                ('user_ip', models.CharField(default='0', max_length=30, verbose_name='用户IP')),
            ],
        ),
        migrations.RemoveField(
            model_name='book',
            name='author',
        ),
        migrations.DeleteModel(
            name='Author',
        ),
        migrations.DeleteModel(
            name='Book',
        ),
    ]
