# Generated by Django 2.1.4 on 2018-12-28 05:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0007_auto_20181228_1314'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ChatInfo',
        ),
        migrations.DeleteModel(
            name='UserInfo',
        ),
    ]
