# Generated by Django 2.1.4 on 2018-12-28 09:04

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('chat', '0008_auto_20181228_1316'),
    ]

    operations = [
        migrations.CreateModel(
            name='Useinfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=32)),
                ('password', models.CharField(max_length=64)),
                ('age', models.IntegerField()),
            ],
        ),
    ]
