# Generated by Django 2.0.2 on 2018-12-28 09:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0009_useinfo'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Useinfo',
        ),
    ]
