# Generated by Django 2.0.2 on 2018-12-28 10:12

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('chat', '0012_auto_20181228_1811'),
    ]

    operations = [
        migrations.CreateModel(
            name='ChatInfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_name', models.CharField(default='匿名', max_length=50, verbose_name='用户名')),
                ('chat_content', models.CharField(default='空', max_length=400, verbose_name='发送的内容')),
            ],
            options={
                'verbose_name': '聊天内容',
                'verbose_name_plural': '聊天内容',
            },
        ),
        migrations.CreateModel(
            name='UserInfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_name', models.CharField(default='匿名用户', max_length=50, verbose_name='用户名')),
                ('user_pwd', models.CharField(max_length=50, verbose_name='用户密码')),
            ],
        ),
    ]
